---
apiVersion: v1
kind: Namespace
metadata:
  name: git-at-home

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-at-home
  template:
    metadata:
      labels:
        app: git-at-home
    spec:
      # FIX: Add a security context to fix file ownership issues.
      securityContext:
        # fsGroup ensures that all files in the volumes are owned by this group ID.
        # The git user's group ID is 1000. This allows sshd to read the
        # authorized_keys file even though it's mounted from a root-owned secret.
        fsGroup: 1000
      initContainers:
        # This initContainer runs first to prepare the volume. It copies the
        # default sshd_config from the image into the shared volume, so that
        # mounting the volume doesn't hide the config file from the main container.
        - name: copy-ssh-config
          image: ghcr.io/neptunehub/git-at-home:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              if [ ! -f /persistent-ssh/sshd_config ]; then
                echo "Initializing sshd_config in volume..."
                cp /etc/ssh/sshd_config /persistent-ssh/sshd_config
              else
                echo "sshd_config already exists in volume."
              fi
          volumeMounts:
            - name: ssh-host-keys
              mountPath: /persistent-ssh
      containers:
        - name: git-server
          image: ghcr.io/neptunehub/git-at-home:latest
          # The command now generates host keys into a persistent volume on first start.
          command: ["/bin/sh", "-c"]
          args:
            - ssh-keygen -A && exec /usr/sbin/sshd -D -e
          ports:
            - containerPort: 22
          volumeMounts:
            # Mount for the user's public key from the secret.
            # This relies on the /home/git/.ssh directory from the original image.
            - name: ssh-keys
              mountPath: /home/git/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
            # Mount for the git repositories.
            - name: git-repos
              mountPath: /git/repos
            # Mount for the server's host keys, which now also contains the config.
            - name: ssh-host-keys
              mountPath: /etc/ssh
      volumes:
        # Volume for the user's public key, with correct permissions.
        - name: ssh-keys
          secret:
            secretName: git-ssh-keys
            defaultMode: 0600
        # This volume now uses a PersistentVolumeClaim for durable storage.
        - name: git-repos
          persistentVolumeClaim:
            claimName: git-repos-pvc
        # Volume to persist the server's host keys for the life of the pod.
        - name: ssh-host-keys
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  # MODIFIED: Changed the service type to LoadBalancer.
  type: LoadBalancer
  selector:
    app: git-at-home
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      # REMOVED: The nodePort is not needed for a LoadBalancer service.

---
# This PersistentVolumeClaim requests durable storage for the git repositories.
# Your cluster's default StorageClass will automatically provision a PersistentVolume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos-pvc
  namespace: git-at-home
spec:
  # ReadWriteOnce is appropriate for a single pod writing to the volume.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Request 1 GiB of storage. You can adjust this size as needed.
      storage: 1Gi
