---
apiVersion: v1
kind: Namespace
metadata:
  name: git-at-home

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-at-home
  template:
    metadata:
      labels:
        app: git-at-home
    spec:
      initContainers:
        # FIX: This initContainer runs first to prepare the volume. It copies the
        # default sshd_config from the image into the shared volume, so that
        # mounting the volume doesn't hide the config file from the main container.
        - name: copy-ssh-config
          image: ghcr.io/neptunehub/git-at-home:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              if [ ! -f /persistent-ssh/sshd_config ]; then
                echo "Initializing sshd_config in volume..."
                cp /etc/ssh/sshd_config /persistent-ssh/sshd_config
              else
                echo "sshd_config already exists in volume."
              fi
          volumeMounts:
            - name: ssh-host-keys
              mountPath: /persistent-ssh
      containers:
        - name: git-server
          image: ghcr.io/neptunehub/git-at-home:latest
          # The command now generates host keys into a persistent volume on first start.
          command: ["/bin/sh", "-c"]
          args:
            - ssh-keygen -A && exec /usr/sbin/sshd -D -e
          ports:
            - containerPort: 22
          volumeMounts:
            # Mount for the user's public key from the secret.
            # This relies on the /home/git/.ssh directory from the original image.
            - name: ssh-keys
              mountPath: /home/git/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
            # Mount for the git repositories.
            - name: git-repos
              mountPath: /git/repos
            # Mount for the server's host keys, which now also contains the config.
            - name: ssh-host-keys
              mountPath: /etc/ssh
      volumes:
        # Volume for the user's public key, with correct permissions.
        - name: ssh-keys
          secret:
            secretName: git-ssh-keys
            defaultMode: 0600
        # Volume for the git repositories. For production, change this to a PVC.
        - name: git-repos
          emptyDir: {}
        # Volume to persist the server's host keys for the life of the pod.
        - name: ssh-host-keys
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  type: NodePort
  selector:
    app: git-at-home
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 32222
