---
apiVersion: v1
kind: Namespace
metadata:
  name: git-at-home

---
# NEW: A Secret to store the git user's password.
# The password is 'changeme' encoded in base64.
apiVersion: v1
kind: Secret
metadata:
  name: git-password-secret
  namespace: git-at-home
type: Opaque
data:
  # To change the password, encode your new password with: echo -n 'newpassword' | base64
  GIT_PASSWORD: Y2hhbmdlbWU=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-at-home
  template:
    metadata:
      labels:
        app: git-at-home
    spec:
      # REMOVED: The initContainer for SSH keys is no longer needed.
      containers:
        - name: git-server
          image: ghcr.io/neptunehub/git-at-home:latest
          # This command sets the git user's password from the secret,
          # then generates host keys and starts the SSH server.
          command: ["/bin/sh", "-c"]
          args:
            - echo "git:$GIT_PASSWORD" | chpasswd && ssh-keygen -A && exec /usr/sbin/sshd -D -e
          env:
            # Load the password from the secret into an environment variable.
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-password-secret
                  key: GIT_PASSWORD
          ports:
            - containerPort: 22
          volumeMounts:
            # Only the git-repos volume is needed now.
            - name: git-repos
              mountPath: /git/repos
      volumes:
        # REMOVED: The secret and home directory volumes for SSH keys are gone.
        # This volume uses a PersistentVolumeClaim for durable storage.
        - name: git-repos
          persistentVolumeClaim:
            claimName: git-repos-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  type: LoadBalancer
  selector:
    app: git-at-home
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22

---
# This PersistentVolumeClaim requests durable storage for the git repositories.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos-pvc
  namespace: git-at-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
