apiVersion: v1
kind: Namespace
metadata:
  name: git-at-home
---
apiVersion: v1
kind: Secret
metadata:
  name: git-password-secret
  namespace: git-at-home
type: Opaque
data:
  GIT_PASSWORD: Y2hhbmdlbWU=  # 'changeme' in base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos-pvc
  namespace: git-at-home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-at-home
  template:
    metadata:
      labels:
        app: git-at-home
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu3
      containers:
        - name: git-server
          image: ghcr.io/neptunehub/git-at-home:latest
          env:
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-password-secret
                  key: GIT_PASSWORD
          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 80
          volumeMounts:
            - name: git-repos
              mountPath: /git/repos
      volumes:
        - name: git-repos
          persistentVolumeClaim:
            claimName: git-repos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: git-at-home
  namespace: git-at-home
spec:
  type: LoadBalancer
  selector:
    app: git-at-home
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
